enum PostActionTypes {
  FETCH_POST_START= 'FETCH_POST_START',
  FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS',
  FETCH_POST_FAILURE = 'FETCH_POST_FAILURE',
  // FETCH_UPDATE_START= 'FETCH_UPDATE_START',
  // FETCH_UPDATE_SUCCESS = 'FETCH_UPDATE_SUCCESS',
  // FETCH_UPDATE_FAILURE = 'FETCH_UPDATE_FAILURE',
  // FETCH_DELETE_START= 'FETCH_DELETE_START',
  // FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS',
  // FETCH_DELETE_FAILURE = 'FETCH_DELETE_FAILURE',
}

export default PostActionTypes;

