enum BlogActionTypes {
  FETCH_BLOGS_START = 'FETCH_BLOGS_START',
  FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS',
  FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE',
  FETCH_ADDITIONAL_BLOGS_START = "FETCH_ADDITIONAL_BLOGS_START",
  FETCH_ADDITIONAL_BLOGS_SUCCESS = "FETCH_ADDITIONAL_BLOGS_SUCCESS",
  FETCH_ADDITIONAL_BLOGS_FAILURE = "FETCH_ADDITIONAL_BLOGS_FAILURE"
}

export default BlogActionTypes;
